<!DOCTYPE html>
<html>
<head>
    <title>Student Webstore</title>
    <meta charset=utf-8>
    <link rel="stylesheet" href="/css/style.css"/>
</head>
<body>
    <a href="/index.php" class="arrow-back">←</a>
    <?php $session = new \App\Model\Session();
    if (!$session->isLoggedIn()):?>
        <div class="login-box">
            <a href="?page=cart_list">You quote</a>
            <a href="?page=customer_login">Login</a>
            <a href="?page=customer_register">Register</a>
        </div>
    <?php else: ?>
         <div class="login-box">
            <p>Welcome, <strong><?php echo $session->getCustomer()->getData('name') ?></strong></p>
             <a href="?page=cart_list">You quote</a>
            <a href="?page=customer_logout">Logout</a>
        </div>
    <?php endif;

    $this->renderTemplate();
    ?>
</body>
</html>
