<h1>Login for admin panel</h1>

<form action="?page=admin_login" method="POST">

    <div>
        <label for="name">Login</label>
        <input type="text" id="login" name="admin[login]" />
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="admin[password]" />
    </div>

    <input type="submit" value="Login">
    <?php if ($this->get('error')): ?>
        <p class="error">Incorrect login or password</p>
    <?php endif; ?>
</form>