<div class="shopping-cart">
    <?php

    $items = $this->get('items');

    if (!count($items->getItems())): ?>
        <h3>Your cart is empty!</h3>
    <?php endif; ?>

    <?php foreach ($items as $item):
        $product = $item->getProduct();?>
        <a href="/?page=product_view&id=<?php echo $product->getId() ?>"><strong><?php echo $product->getName(); ?></strong></a>
        <p><?php echo $item->getQty() ?> pieces</p>
        <a class="change" href="/?page=cart_plus&id=<?php echo $product->getId() ?>">+</a>
        <?php if ($item->getQty() > 1): ?>
            <a class="change" href="/?page=cart_minus&id=<?php echo $product->getId() ?>">-</a>
        <?php endif; ?>
        <br>
        <?php if ($product->isSpecialPriceApplied()): ?>
            <p class="strike"><?php echo $product->getPrice(); ?></p>
            <p><?php echo $product->getSpecialPrice(); ?> $</p>
            <p class="total">Total: <?php echo $product->getSpecialPrice() * $item->getQty(); ?> $</p>
        <?php else: ?>
            <p><?php echo $product->getPrice(); ?> $</p>
            <p class="total">Total: <?php echo $product->getPrice() * $item->getQty(); ?> $</p>
        <?php endif; ?>
        <a href="/?page=cart_delete&id=<?php echo $product->getId() ?>" class="option">Delete from cart</a>
    <?php endforeach; ?>

    <?php if (count($items->getItems())): ?>
        <h2 class="checkout"><a href="/?page=checkout_address">Checkout →</a></h2>
    <?php endif; ?>

</div>
