<h1>Select shipping method</h1>

<form action="?page=checkout_shipping" class="shipping" method="POST">

    <div>
        <?php foreach($this->get('methods') as $method): ?>
            <label><input type="radio" name="method" value="<?php echo $method['code'] ?>"><?php echo $method['price'] ?>$ (<?php echo $method['label'] ?>)</label>
        <?php endforeach; ?>
    </div>

    <input type="submit" value="Save">
</form>
