<h1>Select method</h1>

<form action="?page=checkout_shipping" class="shipping" method="POST">

    <div>
        <?php foreach($this->get('methods') as $method): ?>
            <label><input type="radio" name="method" value="<?php echo $method['code'] ?>"><?php echo $method['price'] ?>$ (<?php echo $method['code'] ?>)</label>
        <?php endforeach; ?>
    </div>

    <input type="submit" value="Save">
</form>

<h2 class="checkout"><a href="/?page=checkout_shipping">Checkout →</a></h2>
