<h1>Join Our Site</h1>

<form action="?page=customer_register" method="POST">
    <div>
        <label for="email">Email</label>
        <input type="text" id="email" name="customer[email]" />
    </div>
    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="customer[name]" />
    </div>
    <div>
        <label for="surname">Surname</label>
        <input type="text" id="surname" name="customer[surname]" />
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="customer[password]" />
    </div>

    <input type="submit" value="Register">
    <?php if ($this->get('error')): ?>
        <p class="error">Incorrect email or password</p>
    <?php endif; ?>
</form>

