<h1> <?php
    $product = $this->get('product');
    $pages = $this->get('pages');
    $reviews = $this->get('reviews');
    echo $product->getName(); ?> </h1>
<ul>
    <li class="item clearfix">
        <img src="<?php echo $product->getImage(); ?>" alt=""/>
        <a href="#"><h2><?php echo $product->getName(); ?></h2></a>
        <p><span>SKU:</span> <?php echo $product->getSku(); ?></p>
        <?php if($product->isSpecialPriceApplied()): ?>
            <p class="strike"><span>Цена:</span> <?php echo $product->getPrice(); ?> $</p>
            <p><span>Спец. цена:</span> <?php echo $product->getSpecialPrice(); ?> $</p>
        <?php else: ?>
            <p><span>Цена:</span> <?php echo $product->getPrice(); ?> $</p>
        <?php endif; ?>
        <p><span>Средний рейтинг:</span> <?php echo round($reviews->getAverageRating(), 2); ?></p>
        <a href="/?page=cart_add&id=<?php echo $product->getId(); ?>" class="option">Add to cart</a>
    </li>


     <?php foreach ($reviews as $_review):?>
        <li class="review">
            <p class="name"><span><?php echo $_review->getName(); ?></span></p>
            <?php $email = $_review->getEmail();
                  if ($email): ?>
                <a class="email" href="mailto:<?php echo $email; ?>"><?php echo $email; ?></a>
            <?php endif; ?>
            <p><?php echo $_review->getText(); ?></p>
            <p><span><?php echo $_review->getRating(); ?> / 5</span></p>
        </li>
    <?php endforeach;?>
</ul>

<?php if($pages->pageCount > 1):?>
    <div class="paginator">
    <?php for($i = 1; $i <= $pages->pageCount; $i++): ?>
        <?php if($i == $pages->current): ?>
            <span><?php echo $i; ?></span>
        <?php else: ?>
            <a href="/?page=product_view&id=<?php echo $product->getId();?>&p=<?php echo $i?>"><?php echo $i; ?></a>
        <?php endif; ?>
    <?php endfor; ?>
</div>
<?php endif;?>

<h2 class="product-review-header">Write you product review!</h2>
<form class="product-review" action="/?page=productReview_add" method="post">
    <input type="hidden" name="product_id" value="<?php echo $product->getId() ?>">
    <input type="hidden" name="token" value="<?php echo $this->session()->getToken() ?>">
    <input type="text" name="name" placeholder="You name">
    <input type="text" name="email" placeholder="You email">
    <p><input type="radio" name="rating" value="1">1</p>
    <p><input type="radio" name="rating" value="2">2</p>
    <p><input type="radio" name="rating" value="3">3</p>
    <p><input type="radio" name="rating" value="4">4</p>
    <p><input type="radio" name="rating" value="5">5</p>
    <textarea name="text" cols="30" rows="10" placeholder="You product review"></textarea>
    <input type="submit" value="Send">
</form>


