<!DOCTYPE html>
<html>
<head>
    <title>Student Webstore</title>
    <meta charset=utf-8>
    <link rel="stylesheet" href="/css/style.css"/>
</head>
<body>
<h1>Our Product List</h1>
<ul>
    <?php foreach ($product as $_product): ?>
        <li class="item clearfix">
            <img src="<?php echo $_product->getImage(); ?>" alt=""/>
            <h2><?php echo $_product->getName(); ?></h2>
            <p>Sku: <?php echo $_product->getSku(); ?></p>
            <p>Price: <?php echo $_product->getPrice(); ?></p>
            <p>Special Price: <span><?php echo $_product->getSpecialPrice(); ?></p>
        </li>
    <?php endforeach; ?>
</ul>
</body>
</html>
