<h1> <?php echo $product->getName(); ?> </h1>
<ul>
    <li class="item clearfix">
        <img src="<?php echo $product->getImage(); ?>" alt=""/>
        <a href="#"><h2><?php echo $product->getName(); ?></h2></a>
        <p><span>SKU:</span> <?php echo $product->getSku(); ?></p>
        <?php if($product->isSpecialPriceApplied()): ?>
            <p class="strike"><span>Цена:</span> <?php echo $product->getPrice(); ?> $</p>
            <p><span>Спец. цена:</span> <?php echo $product->getSpecialPrice(); ?> $</p>
        <?php else: ?>
            <p><span>Цена:</span> <?php echo $product->getPrice(); ?> $</p>
        <?php endif; ?>
        <p><span>Средний рейтинг:</span> <?php echo round($reviews->getAverageRating(), 2); ?></p>
        <a href="/?page=shoppingCart_add&id=<?php echo $product->getId(); ?>" class="option">Add to cart</a>
    </li>


        <?php foreach ($reviews as $_review):?>
        <li class="review">
            <p><span><?php echo $_review->getName(); ?></span></p>
            <p><?php echo $_review->getText(); ?></p>
            <p><span><?php echo $_review->getRating(); ?> / 5</span></p>
        </li>
    <?php endforeach;?>
</ul>