<h1>Our Product List</h1>
<ul>
    <?php foreach ($paginator as $_product): ?>
        <?php $_product = new \App\Model\Product($_product); ?>
        <li class="item clearfix">
            <img src="<?php echo $_product->getImage(); ?>" alt=""/>
            <a href="/?page=product_view&id=<?php echo $_product->getId(); ?>"><h2><?php echo $_product->getName(); ?></h2></a>
            <p><span>SKU:</span> <?php echo $_product->getSku(); ?></p>

            <?php if($_product->isSpecialPriceApplied()): ?>
                <p class="strike"><span>Цена:</span> <?php echo $_product->getPrice(); ?> $</p>
                <p><span>Спец. цена:</span> <?php echo $_product->getSpecialPrice(); ?> $</p>
            <?php else: ?>
                <p><span>Цена:</span> <?php echo $_product->getPrice(); ?> $</p>
            <?php endif; ?>
            <a href="/?page=shoppingCart_add&id=<?php echo $_product->getId(); ?>" class="option">Add to cart</a>
        </li>
    <?php endforeach; ?>
</ul>

<div class="paginator">
    <?php for($i = 1; $i <= $paginator->count(); $i++):?>
        <?php if($i == $paginator->getCurrentPageNumber()): ?>
            <span><?php echo $i; ?></span>
        <?php else: ?>
            <a href="/?p=<?php echo $i?>"><?php echo $i; ?></a>
        <?php endif; ?>
    <?php endfor; ?>
</div>